syntax = "proto3";

package proto;

option go_package = "github.com/memap-project/memap-proto/gen/memapv1/go";

enum CommandType {
  UNKNOWN = 0;

  CREATE = 1;
  DROP = 2;
  ERASE = 3;
  FLUSH = 4;

  GET = 5;
  SET = 6;
  DEL = 7;
  EXPIRE = 8;
  TTL = 9;

  HGET = 10;
  HSET = 11;
  HDEL = 12;
  HEXPIRE = 13;
  HTTL = 14;
  HEXIST = 15;
  HLEN = 16;
  HKEYS = 17;
  HVALS = 18;
  HFGET = 19;
  HFSET = 20;
  HFDEL = 21;

  CINIT = 23;
  CSLIMIT = 24;
  CGLIMIT = 25;
  CGET = 26;
  CDEL = 27;
  CEXPIRE = 28;
  CTTL = 29;
  CINCRBY = 30; //
  CDECRBY = 31; //

  BINIT = 32;
  BPUSH = 33;
  BPOP = 34;
  BAT = 35;
  BSLICE = 36;
  BPEEK = 37;
  BBACK = 38;
  BCAP = 39;
  BLEN = 40;
  BRESET = 41;
  BDEL = 42;
  BEXPIRE = 43;
  BTTL = 44;

  PING = 45;
}

message Request {
  CommandType command = 1;
  string namespace = 2; // commonly-used
  string key = 3; // commonly-used
  string string_value = 4; // commonly-used
  int64 int_value = 5; // for CINCRBY/CDECRBY
  string field = 6; // for HFSET/HFGET/HFDEL
  int64 ttl = 7; // commonly-used
  int64 limit = 8; // for CINIT/CSLIMIT/CGLIMIT and BINIT (capacity)
}

message Response {
  bool success = 1; // commonly-used
  string string_value = 2; // commonly-used
  map<string, string> map_value = 3; // for HGET
  repeated string slice_value = 4; // for HKEYS/HVALS/BSLICE
  int64 int_value = 5; // commonly-used
  string error = 6; // commonly-used
}
