syntax = "proto3";

package proto;

option go_package = "github.com/memap-project/memap-proto/gen/memapv1/go";

enum CommandType {
  UNKNOWN = 0;

  CREATE = 1;
  DROP = 2;
  ERASE = 3;
  FLUSH = 4;

  GET = 5;
  SET = 6;
  DEL = 7;
  EXPIRE = 8;
  TTL = 9;

  HGET = 10;
  HSET = 11;
  HDEL = 12;
  HEXPIRE = 13;
  HTTL = 14;
  HEXIST = 15;
  HLEN = 16;
  HKEYS = 17;
  HVALS = 18;
  HFGET = 19;
  HFSET = 20;
  HFDEL = 21;

  CSLIMIT = 22;
  CGLIMIT = 23;
  CGET = 24;
  CDEL = 25;
  CEXPIRE = 26;
  CTTL = 27;
  CINCRBY = 28;
  CDECRBY = 29;

  BINIT = 30;
  BPUSH = 31;
  BPOP = 32;
  BAT = 33;
  BSLICE = 34;
  BPEEK = 35;
  BBACK = 36;
  BCAP = 37;
  BLEN = 38;
  BRESET = 39;
  BDEL = 40;
  BEXPIRE = 41;
  BTTL = 42;

  PING = 43;
}

message Request {
  CommandType command = 1;
  string namespace = 2; // commonly-used
  string key = 3; // commonly-used
  string string_value = 4; // commonly-used
  int64 int_value = 5; // for CINCRBY/CDECRBY
  string field = 6; // for HFSET/HFGET/HFDEL
  int64 ttl = 7; // commonly-used
  int64 limit = 8; // for CSLIMIT/CGLIMIT and BINIT (capacity)
}

message Response {
  bool success = 1; // commonly-used
  string string_value = 2; // commonly-used
  map<string, string> map_value = 3; // for HGET
  repeated string slice_value = 4; // for HKEYS/HVALS/BSLICE
  int64 int_value = 5; // commonly-used
  string error = 6; // commonly-used
}
