syntax = "proto3";

package proto;

option go_package = "github.com/memap-project/memap-proto/gen/memapv1/go";

enum CommandType {
  UNKNOWN = 0;

  CREATE_NS = 1;
  DELETE_NS = 2;
  ERASE = 3;
  FLUSH = 4;

  GET = 5;
  SET = 6;
  DEL = 7;
  EXPIRE = 8;
  TTL = 9;

  HGET = 10;
  HSET = 11;
  HDEL = 12;
  HEXPIRE = 13;
  HTTL = 14;
  HEXIST = 15;
  HLEN = 16;
  HKEYS = 17;
  HVALS = 18;

  HFGET = 19;
  HFSET = 20;
  HFDEL = 21;

  PING = 22;
}

message Request {
  CommandType type = 1;
  string key = 2;
  string value = 3;
  string field = 4;
  string namespace_name = 5;
  int64 ttl_seconds = 6;
}

message Response {
  bool success = 1;
  string value = 2;
  map<string, string> hash_value = 3;
  repeated string list_values = 4;
  int64 int_value = 5;
  string error_message = 6;
}
